New approach

diff --git a/.github/workflows/full_build.yml b/.github/workflows/full_build.yml
--- a/.github/workflows/full_build.yml
+++ b/.github/workflows/full_build.yml
@@ -1,27 +1,66 @@
-name: demisto/dockerfiles-info/full_build
+name: Docker Repository Update
+
 on:
   push:
     branches:
-#    - master
-     - '**'
+      - master
+  pull_request:
+    branches:
+      - master
+  schedule:
+    - cron: '0 1 * * *'
+
 jobs:
-  update_repo_info:
+  update_docker_repo_info:
     runs-on: ubuntu-latest
-    container:
-      image: devdemisto/dockerbuild:1.0.0.25778
+
     steps:
-    - uses: actions/checkout@v4.1.0
-#     # 'setup_remote_docker' was not transformed because there is no suitable equivalent in GitHub Actions
-    # Ensure parameter if_key_exists is set correctly
-    - name: Install SSH key
-      uses: shimataro/ssh-key-action@v2.6.1
-      with:
-        key: "${{ secrets.CIRCLE_CI_SSH_KEY }}"
-        name: circle_ci_id_rsa
-        known_hosts: "${{ secrets.CIRCLE_CI_KNOWN_HOSTS }}"
-        if_key_exists: fail
-    - name: Update Docker Repo Info
-      run: "./update-repository-info.sh"
-    - uses: actions/upload-artifact@v4.1.0
-      with:
-        path: artifacts
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Set up Python environment
+        uses: actions/setup-python@v4
+        with:
+          python-version: '3.x'
+
+      - name: Set up pipenv
+        run: |
+          python -m pip install --upgrade pip
+          pip install pipenv
+
+      - name: Install dependencies
+        run: pipenv install
+
+      - name: Run update-docker-repo-info script
+        run: pipenv run ./update-docker-repo-info.py
+
+      - name: Configure Git for commit
+        run: |
+          git config --global user.email "dc-builder@users.noreply.github.com"
+          git config --global user.name "dc-builder"
+
+      - name: Check for changes
+        id: git_status
+        run: |
+          git status --short > git_changes.txt
+          cat git_changes.txt
+
+      - name: Upload artifacts (if changes)
+        if: steps.git_status.outputs.changes != ''
+        run: |
+          mkdir -p artifacts
+          cat git_changes.txt | awk '{print $2}' | sed 's:/*$::' | xargs -I {} cp -rf {} artifacts/. || echo "cp failed for some reason. continue..."
+        continue-on-error: true
+
+      - name: Commit and push changes
+        if: steps.git_status.outputs.changes != ''
+        run: |
+          git add .
+          git commit -m "$(date): auto repo info update [skip ci]"
+          git push
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        continue-on-error: true
+
+      - name: Print completion message
+        run: echo "Docker repository update complete."
